### ISSUE TITLE
List existing entities for new nodes.

### ISSUE THREAD

**Issue by chicoribas** [archbuddy/frontend#22]
When a new node is dropped on a diagram, should be possible to select an existing entity for that new node.

The idea is:
- In the AddNodeModal, display a checkbox, with two options:
  - Existing Entity
  - New Entity

- If the user select existing entity, a list of existing entities must be shown and be selected by user.
- If New Entity is select, the user must input Name and Description. When user click on OK, a new entity is created.

**Comment by brunopenso** [comment]
@chicoribas I understand that the usar should type the and not select if exists or not.

The main reason is because the user could not have any idea if the system exists or not 

And talking about the search I think we need to have a lexical search to improve how the user search
